security:
    providers:
        in_memory:
            memory:
                users:
                    user1: { password: user1pass, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~

    encoders:
        SmartworkoutBundle\Entity\User:
            algorithm:          sha1
            encode_as_base64:   false